
import React from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { AssessmentReport, Severity } from '../types';

const Report: React.FC = () => {
  const location = useLocation();
  const { id } = useParams();
  const navigate = useNavigate();
  
  // Try to get report from state, otherwise fetch from localStorage
  let report: AssessmentReport | undefined = location.state?.report;
  
  if (!report) {
    const history = JSON.parse(localStorage.getItem('agridiagnost_history') || '[]');
    report = history.find((h: AssessmentReport) => h.id === id);
  }

  if (!report) {
    return (
      <div className="max-w-4xl mx-auto px-6 py-24 text-center">
        <h2 className="text-2xl font-serif text-primary mb-4">Report Not Found</h2>
        <button onClick={() => navigate('/history')} className="text-secondary underline">Return to History</button>
      </div>
    );
  }

  const severityColor = {
    [Severity.LOW]: 'bg-olive',
    [Severity.MODERATE]: 'bg-moderate',
    [Severity.SEVERE]: 'bg-severe'
  };

  const severityText = {
    [Severity.LOW]: 'Low Impact',
    [Severity.MODERATE]: 'Moderate Risk',
    [Severity.SEVERE]: 'Critical / Severe'
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-warmSand py-16 px-6">
      <div className="max-w-5xl mx-auto">
        
        <div className="flex justify-between items-end mb-8 no-print">
          <div>
            <h1 className="text-4xl font-serif text-primary">Condition Assessment Report</h1>
            <p className="text-mutedGray">Generated by AgriDiagnost Research Systems</p>
          </div>
          <button 
            onClick={handlePrint}
            className="px-6 py-3 bg-white border border-primary text-primary font-bold rounded-subtle hover:bg-primary hover:text-white transition-all text-sm"
          >
            Download Full Report (PDF)
          </button>
        </div>

        {/* Printable Section */}
        <div className="printable bg-white shadow-lg rounded-subtle overflow-hidden">
          {/* Official Header */}
          <div className="border-t-[6px] border-primary p-8 md:p-12 border-b border-gray-100 bg-offWhite/30">
            <div className="flex justify-between items-start mb-10">
              <div>
                <span className="text-xs font-bold text-mutedGray uppercase tracking-widest block mb-2">Technical Analysis Result</span>
                <h2 className="text-3xl font-serif text-charcoal">{report.diagnosis.diseaseName}</h2>
              </div>
              <div className="text-right">
                <div className="text-sm font-bold text-primary mb-1">ID: {report.id}</div>
                <div className="text-xs text-mutedGray">{report.date}</div>
              </div>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div>
                <span className="text-[10px] uppercase font-bold text-mutedGray tracking-wider">Crop Type</span>
                <p className="font-semibold text-charcoal">{report.cropType}</p>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-mutedGray tracking-wider">Location</span>
                <p className="font-semibold text-charcoal">{report.location}</p>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-mutedGray tracking-wider">Soil Composition</span>
                <p className="font-semibold text-charcoal">{report.soilType}</p>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-mutedGray tracking-wider">Severity Level</span>
                <div className="flex items-center space-x-2 mt-1">
                  <div className={`w-3 h-3 rounded-full ${severityColor[report.diagnosis.severity as Severity || Severity.LOW]}`} />
                  <p className="font-bold text-sm">{report.diagnosis.severity}</p>
                </div>
              </div>
            </div>
          </div>

          <div className="p-8 md:p-12 space-y-12">
            {/* Condition Identification */}
            <section>
              <h3 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4 uppercase tracking-wide text-primary">01. Condition Identification</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="md:col-span-2">
                  <p className="text-charcoal leading-relaxed mb-4">
                    {report.diagnosis.description}
                  </p>
                  <div className="inline-block bg-offWhite px-4 py-2 rounded-subtle border border-gray-100">
                    <span className="text-xs font-bold text-mutedGray uppercase mr-2">Confidence Level:</span>
                    <span className="font-bold text-primary">{(report.diagnosis.confidence * 100).toFixed(1)}%</span>
                  </div>
                </div>
                {report.imageUrl && (
                  <div className="no-print">
                    <img src={report.imageUrl} alt="Analyzed specimen" className="w-full rounded-subtle grayscale-[0.5] border border-gray-200" />
                  </div>
                )}
              </div>
            </section>

            {/* Pathological Indicators */}
            <section className="grid grid-cols-1 md:grid-cols-2 gap-12">
              <div>
                <h3 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4 uppercase tracking-wide text-primary">02. Pathological Indicators</h3>
                <ul className="space-y-3">
                  {report.symptoms.map((s, i) => (
                    <li key={i} className="flex items-start space-x-3 text-sm text-charcoal leading-snug">
                      <span className="mt-1.5 w-1.5 h-1.5 bg-gray-400 flex-shrink-0" />
                      <span>{s}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4 uppercase tracking-wide text-primary">03. Probable Etiology</h3>
                <ul className="space-y-3">
                  {report.causes.map((c, i) => (
                    <li key={i} className="flex items-start space-x-3 text-sm text-charcoal leading-snug">
                      <span className="mt-1.5 w-1.5 h-1.5 bg-gray-400 flex-shrink-0" />
                      <span>{c}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </section>

            {/* Intervention Protocols */}
            <section>
              <h3 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4 uppercase tracking-wide text-primary">04. Recommended Intervention Protocols</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 bg-offWhite p-6 rounded-subtle border border-gray-100">
                <div className="space-y-4">
                  <div>
                    <span className="text-[10px] uppercase font-bold text-mutedGray block mb-1">Standard Treatment</span>
                    <p className="text-sm font-semibold">{report.treatment.chemical}</p>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-bold text-mutedGray block mb-1">Dosage Guidance</span>
                    <p className="text-sm">{report.treatment.dosage}</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <span className="text-[10px] uppercase font-bold text-mutedGray block mb-1">Organic Alternative</span>
                    <p className="text-sm font-semibold text-secondary">{report.treatment.organic}</p>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-bold text-mutedGray block mb-1">Application Frequency</span>
                    <p className="text-sm">{report.treatment.frequency}</p>
                  </div>
                </div>
              </div>
            </section>

            {/* Preventive Measures */}
            <section>
              <h3 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4 uppercase tracking-wide text-primary">05. Preventive Advisory</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {report.preventiveMeasures.map((m, i) => (
                  <div key={i} className="p-4 border border-gray-100 bg-white rounded-subtle">
                    <p className="text-sm text-mutedGray leading-relaxed">{m}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Official Notice */}
            <div className="bg-severe/5 border-l-4 border-severe p-6 text-severe">
              <h4 className="font-bold text-sm uppercase mb-2">Advisory Notice</h4>
              <p className="text-xs leading-relaxed">
                Consult a certified agricultural officer or government extension agent before applying chemical treatments. This assessment is based on automated pattern analysis and should be verified via laboratory testing for large-scale interventions.
              </p>
            </div>

            {/* Signature Section */}
            <div className="pt-16 grid grid-cols-2 gap-24">
              <div className="border-t border-gray-400 pt-4">
                <span className="text-xs font-bold text-mutedGray uppercase">Reporting Officer Signature</span>
              </div>
              <div className="border-t border-gray-400 pt-4">
                <span className="text-xs font-bold text-mutedGray uppercase">Institutional Seal</span>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-12 text-center no-print">
           <button 
             onClick={() => navigate('/dashboard')}
             className="text-primary font-bold hover:underline"
           >
             ← Initiate Another Assessment
           </button>
        </div>
      </div>
    </div>
  );
};

export default Report;
